GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs/
content-type: application/json

{
    "title": "My Book",
    "author": "mine",
    "url":"myurl",
    "likes":"50000"
}

###

DELETE http://localhost:3003/api/blogs/64e863614cb79507e9d02816