GET http://localhost:3003/api/users

###

GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs/
content-type: application/json
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1bGFsIiwiaWQiOiI2NGVlMTcyZjM4ODEzNWQwYjU1ZmY0NzMiLCJpYXQiOjE2OTUyMDUxMTUsImV4cCI6MTY5NTIwODcxNX0.TRnl0GTKxick-U0EBBO6_BMawrXjNwQWUbqgprlNQMU

{
    "title": "pratikshya2 blog",
    "author": "bharat",
    "url":"myurl"
    
}

###
POST http://localhost:3003/api/users
Content-Type: application/json


{
  "username": "pratikshya",
  "name": "Hemlal Dulal",
  "password": "dulal123"
}
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "dulal",
  "password": "dulal123"
}

###

PUT http://localhost:3003/api/blogs/64e8655b27fd6f847bf2f934
content-type: application/json

{
    "title": "My Book",
    "author": "yourBook",
    "url":"myurl",
    "likes":"50000"
}

###

DELETE http://localhost:3003/api/blogs/650ac4d8ec1f7d0d923bf5eb
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1bGFsIiwiaWQiOiI2NGVlMTcyZjM4ODEzNWQwYjU1ZmY0NzMiLCJpYXQiOjE2OTUyMDUxMTUsImV4cCI6MTY5NTIwODcxNX0.TRnl0GTKxick-U0EBBO6_BMawrXjNwQWUbqgprlNQMU
