GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Ramanujan",
    "number": "8493893"
}

###
DELETE http://localhost:3001/api/persons/3
